sdl.harvard.geospatial: # {group_id}.{name} from the knime.yml
  src: <LOCAL_PATH_TO>\knime-python-spatial-statistic-nodes\knime_extension # Local path to folder containing the extension files
  conda_env_path: <LOCAL_PATH_TO>\my_python_env # Path to the local installed Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform